# Generated by Django 5.0.6 on 2024-06-15 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.FileField(upload_to='documents/')),
                ('enrolment_certificate', models.FileField(upload_to='documents/')),
                ('internship_start_date', models.DateField()),
                ('internship_end_date', models.DateField()),
                ('internship_agreement', models.FileField(upload_to='documents/')),
                ('internship_insurance', models.FileField(upload_to='documents/')),
                ('resume', models.FileField(upload_to='documents/')),
                ('cover_letter', models.FileField(upload_to='documents/')),
                ('isModifiable', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('education_level', models.CharField(choices=[('bac1', 'Bac + 1'), ('bac2', 'Bac + 2'), ('bac3', 'Bac + 3'), ('bac4', 'Bac + 4'), ('bac5', 'Bac + 5'), ('bac6', 'Bac + 6'), ('bac7', 'Bac + 7'), ('bac8', 'Bac + 8')], max_length=255)),
                ('isModifiable', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
