# Generated by Django 5.0.6 on 2024-06-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrativeinformation',
            old_name='isModifiable',
            new_name='is_modifiable',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='isModifiable',
            new_name='is_modifiable',
        ),
    ]
